# Generated by Django 5.2.7 on 2025-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
    ]
