# Generated by Django 5.2.7 on 2025-11-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alter_reserva_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.lugar'),
        ),
    ]
